# Generated by Django 6.0.1 on 2026-04-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("title", "company", "location")},
            },
        ),
    ]
